version: "3.4"

services:
  backend:
    image: hseeberger/scala-sbt
    working_dir: /opt/order-processing
    command: "sbt '~ run'"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ".:/opt/order-processing"
  frontend:
    build: .docker/frontend
    command: "yarn run serve-frontend"
    ports:
      - "4200:4200"
    volumes:
      - ".:/opt/order-processing"
